### ISSUE TITLE
sqf-html-dialog won't run

### ISSUE THREAD

**Issue by hschmull** [dita-semia/XsltGui#4]
@PStellmann

in my installation (I only cloned the repository ans loaded the XPR) the pther examples run fine but

`sqf-html-dialog-sch.xsl` throws the validation-warning:

> W [Saxon-PE 9.6.0.7] Invalid configuration property extensionElement. Supplied value 'org.DitaSemia.XsltGui.SaxonFactory', required value is the name of a class that implements 'com.saxonica.xsltextn.ExtensionElementFactory': Failed to load org.DitaSemia.XsltGui.SaxonFactory

**Comment by PStellmann** [comment]
Currently it's not possible to add external libraries to an oXygen validation scenario (as you can do for transformation scenarios). Thus, you have to put the DitaSemiaXsltGui.jar in the oxygen lib folder so that Saxon will find it.

**Comment by hschmull** [comment]
> put the DitaSemiaXsltGui.jar in the oxygen lib folder

that's what I did. The Problem seems not to be that the lib cant'n be found, but something about the config-File. Seems it names a _factory_ instead of the name of a _class_ that implements it (whatever that may mean…)

**Comment by PStellmann** [comment]
Sicne all samples use the same config file and you said the other samples work, I don't expect the problem there. The factory class tells Saxon which specific class to use for which instruction (e.g. class GuiHtmlDialog for instruction html-dialog).

Some random thoughts:
- The lib is in the same folder where the lib oxygen.jar is, right?
- Which oXygen version are you using?
- Restart oXygen after you copied the lib.
- Test the SQF sample [register-key-oxy](https://github.com/schematron-quickfix/sqf/tree/master/samples/register-key-oxy) which requires the lib [SqfOxyUtil.jar](https://github.com/schematron-quickfix/sqf/blob/master/samples/SqfOxyUtil/java/SqfOxyUtil.jar) to be in the class path - but no configuration.

**Comment by hschmull** [comment]
> - Restart oXygen after you copied the lib.
> 
> it' so simple…

thank you, fine!

**Comment by PStellmann** [comment]
:)

Added a hint to restart oXygen after copying the file in the README.md
